name: "olmo3-1b-5xC-dclm-pstar-002-hlr-dolma2"
description: "OLMo3 1b@5xC dclm-baseline p* mix"
budget: "ai2/oe-training"
workspace: "ai2/oe-data"
nodes: 4
gpus: 8
preemptible: true
max_tokens: 127_939_584_000
global_batch_size: 2097152
rank_microbatch_size: 32768
sequence_length: 4096
seed: 1337
model: "olmo2_1B_v2"
tokenizer: "dolma2"
priority: high
eval_interval: 250
learning_rate: 1.8e-3
cluster: ai2/augusta
downstream_evaluators:
  - olmo2_dev_1b
dataset:
  sources:
    - name: adult_content
      target_ratio: 0.0000497999482706765
      repetition_factor: 2.0
      paths:
        - "s3://ai2-llm/preprocessed/dclm/baseline_topic_ft_lr05_ng2_n3M6_ova_20pct/allenai/dolma2-tokenizer/adult_content/**/*.npy"
    - name: art_and_design
      target_ratio: 0.0008890156319389095
      repetition_factor: 2.0
      paths:
        - "s3://ai2-llm/preprocessed/dclm/baseline_topic_ft_lr05_ng2_n3M6_ova_20pct/allenai/dolma2-tokenizer/art_and_design/**/*.npy"
    - name: crime_and_law
      target_ratio: 0.016186555467287898
      repetition_factor: 2.0
      paths:
        - "s3://ai2-llm/preprocessed/dclm/baseline_topic_ft_lr05_ng2_n3M6_ova_20pct/allenai/dolma2-tokenizer/crime_and_law/**/*.npy"
    - name: education_and_jobs
      target_ratio: 0.000810837888896179
      repetition_factor: 2.0
      paths:
        - "s3://ai2-llm/preprocessed/dclm/baseline_topic_ft_lr05_ng2_n3M6_ova_20pct/allenai/dolma2-tokenizer/education_and_jobs/**/*.npy"
    - name: electronics_and_hardware
      target_ratio: 0.0007234640858286977
      repetition_factor: 2.0
      paths:
        - "s3://ai2-llm/preprocessed/dclm/baseline_topic_ft_lr05_ng2_n3M6_ova_20pct/allenai/dolma2-tokenizer/electronics_and_hardware/**/*.npy"
    - name: entertainment
      target_ratio: 0.007313197890536659
      repetition_factor: 2.0
      paths:
        - "s3://ai2-llm/preprocessed/dclm/baseline_topic_ft_lr05_ng2_n3M6_ova_20pct/allenai/dolma2-tokenizer/entertainment/**/*.npy"
    - name: fashion_and_beauty
      target_ratio: 0.0000411900615375631
      repetition_factor: 2.0
      paths:
        - "s3://ai2-llm/preprocessed/dclm/baseline_topic_ft_lr05_ng2_n3M6_ova_20pct/allenai/dolma2-tokenizer/fashion_and_beauty/**/*.npy"
    - name: finance_and_business
      target_ratio: 0.0002518954652144411
      repetition_factor: 2.0
      paths:
        - "s3://ai2-llm/preprocessed/dclm/baseline_topic_ft_lr05_ng2_n3M6_ova_20pct/allenai/dolma2-tokenizer/finance_and_business/**/*.npy"
    - name: food_and_dining
      target_ratio: 0.003309783527164619
      repetition_factor: 2.0
      paths:
        - "s3://ai2-llm/preprocessed/dclm/baseline_topic_ft_lr05_ng2_n3M6_ova_20pct/allenai/dolma2-tokenizer/food_and_dining/**/*.npy"
    - name: games
      target_ratio: 0.0017901306583973666
      repetition_factor: 2.0
      paths:
        - "s3://ai2-llm/preprocessed/dclm/baseline_topic_ft_lr05_ng2_n3M6_ova_20pct/allenai/dolma2-tokenizer/games/**/*.npy"
    - name: health
      target_ratio: 0.08071548886090384
      repetition_factor: 2.0
      paths:
        - "s3://ai2-llm/preprocessed/dclm/baseline_topic_ft_lr05_ng2_n3M6_ova_20pct/allenai/dolma2-tokenizer/health/**/*.npy"
    - name: history_and_geography
      target_ratio: 0.0004153629844012423
      repetition_factor: 2.0
      paths:
        - "s3://ai2-llm/preprocessed/dclm/baseline_topic_ft_lr05_ng2_n3M6_ova_20pct/allenai/dolma2-tokenizer/history_and_geography/**/*.npy"
    - name: home_and_hobbies
      target_ratio: 0.008164976242805017
      repetition_factor: 2.0
      paths:
        - "s3://ai2-llm/preprocessed/dclm/baseline_topic_ft_lr05_ng2_n3M6_ova_20pct/allenai/dolma2-tokenizer/home_and_hobbies/**/*.npy"
    - name: industrial
      target_ratio: 0.04250079499662069
      repetition_factor: 2.0
      paths:
        - "s3://ai2-llm/preprocessed/dclm/baseline_topic_ft_lr05_ng2_n3M6_ova_20pct/allenai/dolma2-tokenizer/industrial/**/*.npy"
    - name: literature
      target_ratio: 0.12352451996832144
      repetition_factor: 2.0
      paths:
        - "s3://ai2-llm/preprocessed/dclm/baseline_topic_ft_lr05_ng2_n3M6_ova_20pct/allenai/dolma2-tokenizer/literature/**/*.npy"
    - name: politics
      target_ratio: 0.001356369544468529
      repetition_factor: 2.0
      paths:
        - "s3://ai2-llm/preprocessed/dclm/baseline_topic_ft_lr05_ng2_n3M6_ova_20pct/allenai/dolma2-tokenizer/politics/**/*.npy"
    - name: religion
      target_ratio: 0.0005276023343452912
      repetition_factor: 2.0
      paths:
        - "s3://ai2-llm/preprocessed/dclm/baseline_topic_ft_lr05_ng2_n3M6_ova_20pct/allenai/dolma2-tokenizer/religion/**/*.npy"
    - name: science_math_and_technology
      target_ratio: 0.3859178478770352
      repetition_factor: 2.0
      paths:
        - "s3://ai2-llm/preprocessed/dclm/baseline_topic_ft_lr05_ng2_n3M6_ova_20pct/allenai/dolma2-tokenizer/science_math_and_technology/**/*.npy"
    - name: social_life
      target_ratio: 0.022827908810393156
      repetition_factor: 2.0
      paths:
        - "s3://ai2-llm/preprocessed/dclm/baseline_topic_ft_lr05_ng2_n3M6_ova_20pct/allenai/dolma2-tokenizer/social_life/**/*.npy"
    - name: software
      target_ratio: 0.0008462566212385966
      repetition_factor: 2.0
      paths:
        - "s3://ai2-llm/preprocessed/dclm/baseline_topic_ft_lr05_ng2_n3M6_ova_20pct/allenai/dolma2-tokenizer/software/**/*.npy"
    - name: software_development
      target_ratio: 0.2563807300394595
      repetition_factor: 2.0
      paths:
        - "s3://ai2-llm/preprocessed/dclm/baseline_topic_ft_lr05_ng2_n3M6_ova_20pct/allenai/dolma2-tokenizer/software_development/**/*.npy"
    - name: sports_and_fitness
      target_ratio: 0.04400562004176248
      repetition_factor: 2.0
      paths:
        - "s3://ai2-llm/preprocessed/dclm/baseline_topic_ft_lr05_ng2_n3M6_ova_20pct/allenai/dolma2-tokenizer/sports_and_fitness/**/*.npy"
    - name: transportation
      target_ratio: 0.0011793381768489277
      repetition_factor: 2.0
      paths:
        - "s3://ai2-llm/preprocessed/dclm/baseline_topic_ft_lr05_ng2_n3M6_ova_20pct/allenai/dolma2-tokenizer/transportation/**/*.npy"
    - name: travel_and_tourism
      target_ratio: 0.0002713128763231578
      repetition_factor: 2.0
      paths:
        - "s3://ai2-llm/preprocessed/dclm/baseline_topic_ft_lr05_ng2_n3M6_ova_20pct/allenai/dolma2-tokenizer/travel_and_tourism/**/*.npy"
