name: "suffix-train-olmo2-1xC-30m-dolma2-full-random-uniform-12p-less-tokens-with-evals"
description: "suffix train baseline 30M @ 1xC scale on dolma2 full dataset random uniform 12% less tokens — with in-loop evals"
budget: "ai2/oe-base"
workspace: "ai2/dolma2"
nodes: 1
gpus: 1
preemptible: true
max_tokens: 508_462_067
sequence_length: 2048
global_batch_size: 131072
seed: 1337
learning_rate: 0.007276622186288963
warmup_steps: 400
model: "olmo_30m"
tokenizer: "dolma2"
weka: true
priority: high
cluster: ai2/saturn
lm_evaluator: true
downstream_evaluators:
  - olmo2_dev_1b
eval_interval: 1000
dataset:
  sources:
    - name: dolma2-full
      target_ratio: 1.0
      paths:
        - weka://oe-training-default/ai2-llm/preprocessed/dolma2-0625/v0.1/allenai/dolma2-tokenizer/all-dressed-snazzy2-fixed/**/*.npy
        - weka://oe-training-default/ai2-llm/preprocessed/dolma2-0625/v0.1/allenai/dolma2-tokenizer/arxiv/**/*.npy
        - weka://oe-training-default/ai2-llm/preprocessed/dolma2-0625/v0.1/allenai/dolma2-tokenizer/finemath-3plus/**/*.npy
        - weka://oe-training-default/ai2-llm/preprocessed/dolma2-0625/v0.1/allenai/dolma2-tokenizer/s2pdf_redacted/**/*.npy
        - weka://oe-training-default/ai2-llm/preprocessed/dolma2-0625/v0.1/allenai/dolma2-tokenizer/stack-edu/**/*.npy
        - weka://oe-training-default/ai2-llm/preprocessed/dolma2-0625/v0.1/allenai/dolma2-tokenizer/wikipedia/**/*.npy
