name: &name "olmo25_7b_lc_64k_2T_M100B_r5-midtrain_round3_qwenlike_s2pdf_gzip2080_yoloist-10B"
description: *name
budget: ai2/oe-base
workspace: ai2/long-contexts
cluster: ai2/augusta-google-1
preemptible: true
priority: urgent
nodes: 8
gpus: 8
seed: 4123
gc_interval: 200
warmup_steps: 200
learning_rate: 0.00020712352850360292
metrics_config:
  backend: wandb
  project: olmo3-7b-long-context
  entity: ai2-llm
generate_doc_lengths: true
load_path: gs://ai2-llm/checkpoints/allysone/anneal-round5-100B-olmo25_7b-anneal-2T-f07e3111/step47684
load_state: false
model: olmo25_7b
tokenizer: dolma2
max_tokens: 10000000000
global_batch_size: 4194304
sequence_length: 65536
max_target_sequence_length: 65536
rank_microbatch_size: 65536
scheduler_type: linear
dp_shard_degree: 1
cp_degree: 8
float8: true
eval_interval: 500
model_overrides:
- block.attention.rope.theta=8000000
train_module_overrides:
- scheduler.alpha_f=0.0


dataset:
  sources:
  - name: SC-hqweb
    target_ratio: 0.141666667
    paths:
    - s3://ai2-llm/preprocessed/cc_all_dressed/all_dressed_v3/dclm_plus2_vigilantes-v20-reshard/allenai/dolma2-tokenizer/*.npy
  - name: SC-sponge
    target_ratio: 0.00833336
    paths:
    - s3://ai2-llm/preprocessed/sponge/sponge_63_mixes/eli5_60%_decon_final-reshard/allenai/dolma2-tokenizer/*.npy
  - name: SC-code
    target_ratio: 0.06666668
    paths:
    - s3://ai2-llm/preprocessed/stack-edu-fim/weighted-pl-all-resharded/allenai/dolma2-tokenizer/*.npy
  - name: SC-megamath
    # 10% less the .0268 over 10% for dolminos2math
    target_ratio: 0.04553335
    paths:
    - s3://ai2-llm/preprocessed/megamath_web_pro_max/allenai/dolma2-tokenizer/*.npy
  - name: SC-dolminos2math
    target_ratio: 0.021133333
    paths:
    # 10.7B
    - s3://ai2-llm/preprocessed/all-dolmino-math/round3-reshard/allenai/dolma2-tokenizer/*.npy
  - name: SC-reddit
    target_ratio: 0.03066667
    paths:
    - s3://ai2-llm/preprocessed/reddit-rewrites/densesub-round3-reshard/allenai/dolma2-tokenizer/*.npy
  - name: SC-instruction
    target_ratio: 0.00266667
    paths:
    - s3://ai2-llm/preprocessed/tulu-3-sft-for-olmo-3-midtraining/dolma2-tokenizer/tulu-3-midtrain-v0-data-simple-concat-with-new-line-with-generation-prompt/*.npy
  - name: SC-reasoning
    target_ratio: 0.01666667
    paths:
    - s3://ai2-llm/preprocessed/all-reasoning/round3-reshard/allenai/dolma2-tokenizer/*.npy

  # Qwen-3 like setup. From their tech report:
  #
  # > All models are pre-trained on hundreds of billions of tokens with a sequence length of 32,768
  # > tokens. The long context corpus includes 75% of text between 16,384 to 32,768 tokens in length,
  # > and 25% of text between 4,096 to 16,384 in length.
  #
  # Our model was pretrained with 8k length and we want to extend to 64k, so we tweak the recipe to:
  #
  # - 75% of tokens are between 32,768 and 65,536 tokens in length
  # - 25% of tokens are between 8,192 and 32,768 tokens in length

  - name: LC-s2pdf_32k-64k
    target_ratio: 0.485259637 # 75% of 66.6%
    paths:
      - s3://ai2-llm/preprocessed/s2pdf/dedupe_minhash_v1_with_no_pii_basic_quality/datadelve/norefs_mdtables_v2_denylisted_reshard/length-buckets/compression/allenai/dolma2-tokenizer/2e15/*.npy

  - name: LC-inst_32k-64k
    # we have at most 1474026303 (1.47B) tokens of 32k to 64k inst data, which is 0.01474026303 of hypothetical
    # 100B context extension run. we use that for target ratio
    target_ratio: 0.01474026303 # 75% of 66.6%
    paths:
      - s3://ai2-llm/preprocessed/recommended_yapei_sft/v0/allenai_nemotron-v1-processed_math/length_2e15/allenai/dolma2-tokenizer/*.npy
      - s3://ai2-llm/preprocessed/recommended_yapei_sft/v0/allenai_nemotron-v1-processed_stem/length_2e15/allenai/dolma2-tokenizer/*.npy
      - s3://ai2-llm/preprocessed/recommended_yapei_sft/v0/donmaclean_LongMIT-128K/length_2e15/allenai/dolma2-tokenizer/*.npy
      - s3://ai2-llm/preprocessed/recommended_yapei_sft/v0/nvidia_ChatQA2-Long-SFT-data/length_2e15/allenai/dolma2-tokenizer/*.npy
      - s3://ai2-llm/preprocessed/recommended_yapei_sft/v0/zai-org_LongAlign-10k/length_2e15/allenai/dolma2-tokenizer/*.npy
      - s3://ai2-llm/preprocessed/recommended_yapei_sft/v0/zai-org_LongCite-45k/length_2e15/allenai/dolma2-tokenizer/*.npy


  - name: LC-s2pdf_8k-32k
    target_ratio: 0.1366667 # 25% of 66.6%
    paths:
      - s3://ai2-llm/preprocessed/s2pdf/dedupe_minhash_v1_with_no_pii_basic_quality/datadelve/norefs_mdtables_v2_denylisted_reshard/length-buckets/compression/allenai/dolma2-tokenizer/2e13/*.npy
      - s3://ai2-llm/preprocessed/s2pdf/dedupe_minhash_v1_with_no_pii_basic_quality/datadelve/norefs_mdtables_v2_denylisted_reshard/length-buckets/compression/allenai/dolma2-tokenizer/2e14/*.npy

  - name: LC-inst_8k-32k-no_nemo
    # we have at most 142226492 (1.42B) tokens of 8k to 32k inst data, which is 0.0142226492 of hypothetical
    # 100B context extension run. we use that for target ratio (and pad the rest with nemotron data to get to at least 3% of all data in 8k-32k)
    target_ratio: 0.0142226492 # 25% of 66.6%
    paths:
      - s3://ai2-llm/preprocessed/recommended_yapei_sft/v0/donmaclean_LongMIT-128K/length_2e13/allenai/dolma2-tokenizer/*.npy
      - s3://ai2-llm/preprocessed/recommended_yapei_sft/v0/nvidia_ChatQA2-Long-SFT-data/length_2e13/allenai/dolma2-tokenizer/*.npy
      - s3://ai2-llm/preprocessed/recommended_yapei_sft/v0/zai-org_LongAlign-10k/length_2e13/allenai/dolma2-tokenizer/*.npy
      - s3://ai2-llm/preprocessed/recommended_yapei_sft/v0/zai-org_LongCite-45k/length_2e13/allenai/dolma2-tokenizer/*.npy
      - s3://ai2-llm/preprocessed/recommended_yapei_sft/v0/allean_LongMIT-128K/length_2e14/allenai/dolma2-tokenizer/*.npy
      - s3://ai2-llm/preprocessed/recommended_yapei_sft/v0/nvidia_ChatQA2-Long-SFT-data/length_2e14/allenai/dolma2-tokenizer/*.npy
      - s3://ai2-llm/preprocessed/recommended_yapei_sft/v0/zai-org_LongAlign-10k/length_2e14/allenai/dolma2-tokenizer/*.npy
      - s3://ai2-llm/preprocessed/recommended_yapei_sft/v0/zai-org_LongCite-45k/length_2e14/allenai/dolma2-tokenizer/*.npy

  - name: LC-inst_8k-32k-yes_nemo
    # we have way more from nemotron, but just use a bit.
    target_ratio: 0.0157773508 # 25% of 66.6% + 75% of 66.6%
    paths:
      - s3://ai2-llm/preprocessed/recommended_yapei_sft/v0/allenai_nemotron-v1-processed_math/length_2e13/allenai/dolma2-tokenizer/*.npy
      - s3://ai2-llm/preprocessed/recommended_yapei_sft/v0/allenai_nemotron-v1-processed_stem/length_2e13/allenai/dolma2-tokenizer/*.npy
      - s3://ai2-llm/preprocessed/recommended_yapei_sft/v0/allenai_nemotron-v1-processed_math/length_2e14/allenai/dolma2-tokenizer/*.npy
      - s3://ai2-llm/preprocessed/recommended_yapei_sft/v0/allenai_nemotron-v1-processed_stem/length_2e14/allenai/dolma2-tokenizer/*.npy
