# Example recipe for OLMo3 7b swafix high-throughput configuration for 65k context length
# Needs updates with actual training dataset and hyperparameters
# Benchmarked at 9.3k TPS/device on 2x8 H100s, should scale almost linearly to Nx8 H100s
name: "olmo3_7b_lc_64k_s2pdf-qwen3like_olmo3mix_t8M"
description: "OLMo3 7B w/ swafix trained up to 64k context length with a Qwen3-like mix of s2pdfs and pretraining data from olmo 3 mix"
budget: "ai2/oe-base"
workspace: "ai2/long-contexts"
cluster: ai2/augusta-google-1
preemptible: true
priority: urgent
nodes: 4
gpus: 8
seed: 4123


gc_interval: 200

metrics_config:
  backend: wandb
  project: "olmo3-7b-long-context"
  entity: "ai2-llm"

generate_doc_lengths: true  # enable intra-document masking
# TODO: update to the actual start checkpoint for Long Context extension
load_path: gs://ai2-llm/checkpoints/OLMo3-7B/step297000/model_and_optim/
load_state: false
model: "olmo3_7B_swafix"
tokenizer: "dolma2"
max_tokens: 10_000_000_000  # 10B tokens TODO: update if needed
global_batch_size: 2_097_152  # switched to 2M batch size to match midtraining
sequence_length: &seq_len 65536
max_target_sequence_length: *seq_len
rank_microbatch_size: *seq_len  # must be the same as sequence_length
scheduler_type: linear
warmup_steps: 0
dp_shard_degree: 1  # shard_degree=1 === DDP, shard_degree=world_size === FSDP
cp_degree: 8
float8: true  # NOTE: it might be preferable to disable float8 for anneal / long context training
eval_interval: 500
# downstream_evaluators:
#   - olmo2_dev_1b
model_overrides:
  - block.attention.rope.theta=8000000
dataset:
  sources:
  # This is the best midtraining mix so far (as of 2025-06-30); i've reduced to 1/3 to have 2/3 of LC
  # https://github.com/allenai/olmo-cookbook/blob/13ef591fe202b5657f53f9aa08aec7b470d4c837/src/cookbook/recipes/olmo3-midtraining/anneal-round1-olmo3_7b-with-reasoning-anneal.yaml
  - name: SC-all_dressed-snazzy2
    target_ratio: 0.3333334
    paths:
    - gs://ai2-llm/preprocessed/dolma2-0625/v0.1/allenai/dolma2-tokenizer/all-dressed-snazzy2/**/*.npy

  # We wanna follow a qwen-3 like setup. From their tech report:
  #
  # > All models are pre-trained on hundreds of billions of tokens with a sequence length of 32,768
  # > tokens. The long context corpus includes 75% of text between 16,384 to 32,768 tokens in length,
  # > and 25% of text between 4,096 to 16,384 in length.
  #
  # Our model was pretrained with 8k length and we want to extend to 64k, so we tweak the recipe to:
  #
  # - 75% of tokens are between 32,768 and 65,536 tokens in length
  # - 25% of tokens are between 8,192 and 32,768 tokens in length


  - name: LC-s2pdf_32k-64k
    # 14.07B tokens in this subset in total
    target_ratio: 0.4999999 # 75% of 66.6%
    paths:
    - s3://ai2-llm/preprocessed/s2pdf_dedupe_minhash_v1_with_no_pii_basic_quality_datadelve_norefs_mdtables_v2_denylisted_reshard_length-buckets_sample10pct/allenai/dolma2-tokenizer/length_2e15/*.npy

  - name: LC-s2pdf_8k-32k
    # 19.87B (2e13) + 15.38B (2e14) tokens in this subset
    target_ratio: 0.1666667 # 25% of 66.6%
    paths:
    - s3://ai2-llm/preprocessed/s2pdf_dedupe_minhash_v1_with_no_pii_basic_quality_datadelve_norefs_mdtables_v2_denylisted_reshard_length-buckets_sample10pct/allenai/dolma2-tokenizer/length_2e13/*.npy
    - s3://ai2-llm/preprocessed/s2pdf_dedupe_minhash_v1_with_no_pii_basic_quality_datadelve_norefs_mdtables_v2_denylisted_reshard_length-buckets_sample10pct/allenai/dolma2-tokenizer/length_2e14/*.npy
