name: "olmo2-1b-5xC-dedupablate-minhash-dclm"
description: "OLMo2 1b@5xC, deduplication ablation | minhash dclm "
budget: "ai2/oe-training"
workspace: "ai2/oe-data"
nodes: 4
gpus: 8
preemptible: true
max_tokens: 127_939_584_000 # 1279395840 nonembed params x 20 x 5
sequence_length: 4096
seed: 1337
model: "olmo2_1B_v2"
tokenizer: "dolma2"
priority: urgent
eval_interval: 250
global_batch_size: 2097152
rank_microbatch_size: 32768
learning_rate: 1.8e-3
cluster: ai2/jupiter-cirrascale-2
weka: true
dataset:
  sources:
  - name: minhash_dclm # 141.89B tokens
    target_ratio: 1.0
    paths:
    -  weka://oe-training-default/ai2-llm/pretraining-data/sources/cc_all_dressed/all_dressed_subsamples/deduplication_ablations_v1/minhash_dclm/tokens/dolma2-tokenizer/*.npy


