name: "spring2code-1b-5xC-python-fim-only-hlr"
description: "learn2code 1B@5xC python-only with fim transformation, no prose"
budget: "ai2/oe-training"
workspace: "ai2/oe-data"
nodes: 4
gpus: 8
preemptible: true
max_tokens: 113_184_153_600
sequence_length: 2048
seed: 1337
model: "olmo2_1B"
tokenizer: "dolma2_fim"
priority: high
eval_interval: 250
learning_rate: 1.8e-3
cluster: ai2/jupiter-cirrascale-2
weka: true
dataset:
  sources:
  - name: the-stack-v2-fimv0
    target_ratio: 1
    paths:
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/spring2code-fim-test/allenai/dolma2-tokenizer/**/part-*-00000.npy
   