name: "spring2code-190m-5xC-python-fim-hlr"
description: "learn2code 190M@5xC python-only with fim transformation + dclm prose v2"
budget: "ai2/oe-training"
workspace: "ai2/oe-data"
nodes: 2
gpus: 8
preemptible: true
max_tokens: 19_000_000_000
sequence_length: 2048
seed: 1337
model: "olmo2_190M"
tokenizer: "dolma2_fim"
priority: high
eval_interval: 100
global_batch_size: 1_048_576 # Half of the 1B
learning_rate: 1.8e-3
cluster: ai2/jupiter-cirrascale-2
weka: true
downstream_evaluators:
  - codex_humaneval_gold_bpb_0shot
  - codex_mbpp_gold_bpb_0shot
dataset:
  sources:
  - name: the-stack-v2-fimv0
    target_ratio: 0.85
    paths:
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/spring2code-fim-test/allenai/dolma2-tokenizer/**/part-*-00000.npy
    
  - name: dclm-codeprose-v2
    target_ratio: 0.15
    paths:
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-*-00000.npy
    