name: "olmo2-1b-1T_10b-anneal_dclm-bad-search"
description: "OLMo2 1b 1T ckpt anneal to 10B tokens, DCLM bad search (swarm 62e7dc06 run 87)"
budget: "ai2/oe-data"
workspace: "ai2/oe-data"
nodes: 1
gpus: 8
preemptible: true
max_tokens: 10_000_000_000
global_batch_size: 2097152
sequence_length: 4096
seed: 1337
model: olmo2_1B_v2
tokenizer: "dolma2"
priority: urgent
eval_interval: 250
cluster: ai2/augusta-google-1
rank_microbatch_size: 32768
scheduler_type: linear
warmup_steps: 0
annealing:
  enabled: true
  initial_lr: 0.00036563 # See https://wandb.ai/ai2-llm/olmo-small/runs/kq3x9sam
load_path: gs://ai2-llm/checkpoints/mayeec/olmo2-0425-1b-stage1/step480000/model_and_optim/
load_state: false
dataset:
  sources:
    - name: education_and_jobs
      paths:
        - s3://ai2-llm/preprocessed/dclm/baseline_topic_ft_lr05_ng2_n3M6_ova_20pct/allenai/dolma2-tokenizer/education_and_jobs/**/*.npy
      target_ratio: 0.14285714285714288
    - name: literature
      paths:
        - s3://ai2-llm/preprocessed/dclm/baseline_topic_ft_lr05_ng2_n3M6_ova_20pct/allenai/dolma2-tokenizer/literature/**/*.npy
      target_ratio: 0.33333333333333337
    - name: politics
      paths:
        - s3://ai2-llm/preprocessed/dclm/baseline_topic_ft_lr05_ng2_n3M6_ova_20pct/allenai/dolma2-tokenizer/politics/**/*.npy
      target_ratio: 0.42857142857142855
    - name: software
      paths:
        - s3://ai2-llm/preprocessed/dclm/baseline_topic_ft_lr05_ng2_n3M6_ova_20pct/allenai/dolma2-tokenizer/software/**/*.npy
      target_ratio: 0.09523809523809525