name: "olmo-cookbook-1b-5xC-love2code"
description: "Love2Code model, first stab at a config"
budget: "ai2/oe-training"
workspace: "ai2/oe-data"
nodes: 4
gpus: 8
preemptible: false
max_tokens: 113_184_153_600 # 5xC multiplier
sequence_length: 2048
seed: 1337
learning_rate: 1.8e-3
model: "olmo2_1B"
tokenizer: "dolma2"
priority: urgent
cluster: ai2/jupiter-cirrascale-2
weka: true
dataset:
  sources:
  - name: the-stack-v2-ai2v0
    target_ratio: 1.0
    paths:
    - weka://oe-training-default/ai2-llm/preprocessed/love2code/stack2_v0_trunc/part-001-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/love2code/stack2_v0_trunc/part-004-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/love2code/stack2_v0_trunc/part-006-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/love2code/stack2_v0_trunc/part-007-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/love2code/stack2_v0_trunc/part-008-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/love2code/stack2_v0_trunc/part-008-00001.npy
    - weka://oe-training-default/ai2-llm/preprocessed/love2code/stack2_v0_trunc/part-008-00002.npy
    - weka://oe-training-default/ai2-llm/preprocessed/love2code/stack2_v0_trunc/part-009-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/love2code/stack2_v0_trunc/part-010-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/love2code/stack2_v0_trunc/part-011-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/love2code/stack2_v0_trunc/part-012-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/love2code/stack2_v0_trunc/part-014-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/love2code/stack2_v0_trunc/part-015-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/love2code/stack2_v0_trunc/part-016-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/love2code/stack2_v0_trunc/part-017-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/love2code/stack2_v0_trunc/part-018-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/love2code/stack2_v0_trunc/part-020-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/love2code/stack2_v0_trunc/part-020-00001.npy
    - weka://oe-training-default/ai2-llm/preprocessed/love2code/stack2_v0_trunc/part-022-00003.npy
    - weka://oe-training-default/ai2-llm/preprocessed/love2code/stack2_v0_trunc/part-024-00001.npy
    - weka://oe-training-default/ai2-llm/preprocessed/love2code/stack2_v0_trunc/part-024-00002.npy
    - weka://oe-training-default/ai2-llm/preprocessed/love2code/stack2_v0_trunc/part-025-00001.npy
    - weka://oe-training-default/ai2-llm/preprocessed/love2code/stack2_v0_trunc/part-027-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/love2code/stack2_v0_trunc/part-028-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/love2code/stack2_v0_trunc/part-028-00001.npy
    - weka://oe-training-default/ai2-llm/preprocessed/love2code/stack2_v0_trunc/part-028-00002.npy
    - weka://oe-training-default/ai2-llm/preprocessed/love2code/stack2_v0_trunc/part-028-00003.npy
    - weka://oe-training-default/ai2-llm/preprocessed/love2code/stack2_v0_trunc/part-029-00001.npy
    - weka://oe-training-default/ai2-llm/preprocessed/love2code/stack2_v0_trunc/part-030-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/love2code/stack2_v0_trunc/part-031-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/love2code/stack2_v0_trunc/part-032-00001.npy
    - weka://oe-training-default/ai2-llm/preprocessed/love2code/stack2_v0_trunc/part-034-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/love2code/stack2_v0_trunc/part-035-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/love2code/stack2_v0_trunc/part-037-00001.npy
    - weka://oe-training-default/ai2-llm/preprocessed/love2code/stack2_v0_trunc/part-038-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/love2code/stack2_v0_trunc/part-040-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/love2code/stack2_v0_trunc/part-042-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/love2code/stack2_v0_trunc/part-042-00001.npy
    - weka://oe-training-default/ai2-llm/preprocessed/love2code/stack2_v0_trunc/part-042-00002.npy
    - weka://oe-training-default/ai2-llm/preprocessed/love2code/stack2_v0_trunc/part-043-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/love2code/stack2_v0_trunc/part-045-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/love2code/stack2_v0_trunc/part-046-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/love2code/stack2_v0_trunc/part-047-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/love2code/stack2_v0_trunc/part-048-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/love2code/stack2_v0_trunc/part-048-00002.npy
    - weka://oe-training-default/ai2-llm/preprocessed/love2code/stack2_v0_trunc/part-050-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/love2code/stack2_v0_trunc/part-050-00002.npy
    - weka://oe-training-default/ai2-llm/preprocessed/love2code/stack2_v0_trunc/part-050-00003.npy
