name: "train-SAMPLE-augusta"
description: "Just trying out cookbook + augusta"
budget: "ai2/oe-training"
workspace: "ai2/learn2code"
nodes: 1
gpus: 8
preemptible: true
max_tokens: 113_184_153_600 # 5xC multiplier
sequence_length: 2048
seed: 1337
model: "olmo2_1B"
tokenizer: "dolma2"
priority: high
cluster: ai2/augusta-google-1
weka: false
dataset:
  sources:
  - name: sample
    target_ratio: 1.0
    paths:
      - gs://ai2-llm/preprocessed/love2code/python_only/python_tokens/part-000-00000.npy