name: "olmo-cookbook-1b-5xC-love2code_SAMPLE"
description: "Just a quick check to see if things are working properly"
budget: "ai2/oe-training"
workspace: "ai2/oe-data"
nodes: 1
gpus: 8
preemptible: false
max_tokens: 1_000_000_000 # SIMPLE CHECK AMOUNT 
sequence_length: 2048
seed: 1337
model: "olmo_1b"
tokenizer: "dolma2"
priority: urgent
cluster: ai2/jupiter-cirrascale-2
weka: true
dataset:
  sources:
  - name: the-stack-v2-ai2v0
    target_ratio: 0.85
    paths: # TODO: ADD ACTUAL PATHS
    - s3://ai2-llm/pretraining-data/sources/learn2code/minhash_metadata/love2code-baseline-filtered-20250218_004_minhashed/scratch/trunc_tokens_split/*.npy
  - name: dclm-codeprose-v0
    target_ratio: 0.15
    paths:
    - s3://ai2-llm/pretraining-data/sources/learn2code/minhash_metadata/love2code-baseline-filtered-20250218_004_minhashed/scratch/dclm_codeprose_split/dolma2-tokenizer/*.npy

