name: "olmo-cookbook-1b-5xC-love2code"
description: "Love2Code model, first stab at a config"
budget: "ai2/oe-training"
workspace: "ai2/learn2code"
nodes: 4
gpus: 8
preemptible: false
max_tokens: 113_184_153_600 # 5xC multiplier
sequence_length: 2048
seed: 1337
model: "olmo2_1B"
tokenizer: "dolma2"
priority: urgent
cluster: ai2/jupiter-cirrascale-2
weka: false
dataset:
  sources:
  - name: sample
    target_ratio: 1.0
    paths:
      - gs://ai2-llm/preprocessed/love2code/python_only/python_tokens/part-000-00000.npy