name: "olmo2-1b-5xC-dclm-hlr-dolma2-180k"
description: "OLMo2 1b@5xC dclm-baseline"
budget: "ai2/oe-training"
workspace: "ai2/oe-data"
nodes: 4
gpus: 8
preemptible: true
max_tokens: 113_184_153_600
rank_microbatch_size: 16_384
global_batch_size: 2_097_152
sequence_length: 4096
seed: 1337
model: "olmo2_1B_v2"
tokenizer: "dolma2_180k"
priority: high
eval_interval: 250
learning_rate: 1.8e-3
cluster: ai2/augusta-google-1
weka: true
downstream_evaluators:
  - all
dataset:
  sources:
  - name: dclm-baseline-20pct-superbpe
    target_ratio: 1.0
    paths:
    - weka://oe-training-default/ai2-llm/preprocessed/dclm/baseline_type_topic_classified_20pct/allenai/dolma2-180k-experimental-0.0.1/**/**/part-0*-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/dclm/baseline_type_topic_classified_20pct/allenai/dolma2-180k-experimental-0.0.1/**/**/part-2*-00000.npy

