name: "olmo2-1b-1xC-all-dressed-noDedup"
description: "OLMo2 1b@1xC all dressed flow _without_ any exact deduping. All taken from one cc dump"
budget: "ai2/oe-training"
workspace: "ai2/oe-data"
nodes: 1
gpus: 8
preemptible: true
max_tokens: 25_587_916_800 # 1279395840 nonembed params x 20
sequence_length: 4096
seed: 1337
model: "olmo2_1B_v2"
tokenizer: "dolma2-tokenizer"
priority: high
eval_interval: 250
global_batch_size: 2097152
learning_rate: 1.8e-3
cluster: ai2/jupiter-cirrascale-2
weka: true
downstream_evaluators:
  - all
dataset:
  sources:
  - name: all_dressed
    target_ratio: 1.0
    paths:
    - weka://oe-training-default/mattj/scratch/cc_sanity_check/dolma2-tokenizer/all_dressed/*.npy

