name: "olmo2-1b-5xC-dclm-hlr-superbpe"
description: "OLMo2 1b@5xC dclm-baseline with superbpe tokens"
budget: "ai2/oe-training"
workspace: "ai2/oe-data"
nodes: 4
gpus: 8
preemptible: true
max_tokens: 127_939_584_000
global_batch_size: 3072000
rank_microbatch_size: 24000
sequence_length: 3000
seed: 1337
model: "olmo2_1B_v2"
tokenizer: "superbpe_experimental"
priority: high
eval_interval: 250
warmup_steps: 6100
scheduler_type: wsd
learning_rate: 1.8e-3
cluster: ai2/jupiter-cirrascale-2
weka: true
# downstream_evaluators:
#   - olmo2_dev_1b
dataset:
  sources:
  - name: dclm-baseline-20pct-superbpe
    target_ratio: 1.0
    paths:
    - weka://oe-training-default/ai2-llm/preprocessed/dclm/baseline_type_topic_classified_20pct/allenai/superbpe-experimental-0.1.0/**/**/part-0*-00000.npy

