name: "olmo2-1b-5xC-dclm-hlr-dolma2-180k-wsd"
description: "OLMo2 1b@5xC dclm-baseline"
budget: "ai2/oe-training"
workspace: "ai2/oe-data"
nodes: 4
gpus: 8
preemptible: true
max_tokens: 127_939_584_000
global_batch_size: 2097152
rank_microbatch_size: 16384
sequence_length: 4096
seed: 1337
model: "olmo2_1B_v2"
tokenizer: "dolma2_180k"
priority: high
eval_interval: 250
learning_rate: 1.8e-3
scheduler_type: wsd
cluster: ai2/jupiter-cirrascale-2
load_path: /weka/oe-training-default/ai2-llm/checkpoints/ai2-tylerm/olmo2-1b-5xC-dclm-hlr-dolma2-180k-2ce03c6b/
weka: true
# downstream_evaluators:
#   - olmo2_dev_1b
dataset:
  sources:
  - name: dclm-baseline-20pct-dolma2-180k
    target_ratio: 1.0
    paths:
    - weka://oe-training-default/ai2-llm/preprocessed/dclm/baseline_type_topic_classified_20pct/allenai/dolma2-tokenizer-180k/**/**/part-0*-00000.npy

