name: "olmo2-7b-1xC-dclm-hlr-superbpe"
description: "OLMo2 7b@1xC dclm-baseline with superbpe tokens"
budget: "ai2/oe-training"
workspace: "ai2/oe-data"
nodes: 16
gpus: 8
preemptible: true
max_tokens: 144_284_139_520  # 7_214_206_976 * 20
global_batch_size: 2097152
rank_microbatch_size: 8192
sequence_length: 4096
seed: 1337
model: "olmo2_7B"
tokenizer: "superbpe_experimental"
priority: high
eval_interval: 250
warmup_steps: 6880
learning_rate: 6.8e-4 # sqrt scaling from 1.8e-3
cluster: ai2/jupiter
weka: true
dataset:
  sources:
  - name: dclm-baseline-20pct-superbpe
    target_ratio: 1.0
    paths:
    - weka://oe-training-default/ai2-llm/preprocessed/dclm/baseline_type_topic_classified_20pct/allenai/superbpe-experimental-0.1.0/**/**/part-0*-00000.npy

