name: "olmo2-1b-in-loop-debug"
description: ""
budget: "ai2/oe-training"
workspace: "ai2/oe-data"
nodes: 1
gpus: 8
preemptible: true
max_tokens: 1_000_000_000
global_batch_size: 2097152
rank_microbatch_size: 32768
sequence_length: 4096
seed: 1337
model: "olmo2_1B_v2"
tokenizer: "dolma2"
priority: high
cluster: ai2/saturn-cirrascale
eval_interval: 10
downstream_evaluators:
  - mmlu_stem_val_rc_5shot
weka: true
dataset:
  sources:
  - name: gs-test
    target_ratio: 1.0
    paths:
    - weka://oe-training-default/ai2-llm/preprocessed/dclm/baseline_type_topic_classified_20pct/allenai/dolma2-tokenizer/**/**/part-0*-00000.npy
