name: "olmo2-1b-5xC-dclm-hlr-superbpe"
description: "OLMo2 1b@5xC dclm-baseline with superbpe tokens"
budget: "ai2/oe-training"
workspace: "ai2/oe-data"
nodes: 4
gpus: 8
preemptible: true
max_tokens: 127_939_584_000
sequence_length: 4096
seed: 1337
model: "olmo2_1B_v2"
tokenizer: "superbpe_experimental"
priority: high
eval_interval: 250
learning_rate: 1.8e-3
cluster: ai2/jupiter-cirrascale-2
weka: true
downstream_evaluators:
  - all
dataset:
  sources:
  - name: dclm-baseline-20pct-superbpe
    target_ratio: 1.0
    paths:
    - weka://oe-training-default/ai2-llm/preprocessed/dclm/baseline_type_topic_classified_20pct/allenai/superbpe-olmo3-experimental/**/**/part-0*-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/dclm/baseline_type_topic_classified_20pct/allenai/superbpe-olmo3-experimental/**/**/part-2*-00000.npy

