name: "microanneal-warmup-noisy-reasoning-olmo3-microanneal-100b-5b-lr8.8e-05"
description: "OLMo3 7b 5B noisy reasoning microanneal w/ warmup - continue from 100B - lr 8.8e-05"
budget: "ai2/oe-base"
workspace: "ai2/olmo-3-microanneals"
nodes: 4
gpus: 8
preemptible: true
max_tokens: 5_000_000_000
global_batch_size: 2097152
sequence_length: 8192
seed: 1337
model: "olmo2_7B_swafix"
tokenizer: "dolma2"
priority: high
cluster: ai2/augusta-google-1
rank_microbatch_size: 8192
scheduler_type: linear
warmup_steps: 200
activation_checkpointing: true
learning_rate: 8.8e-05
annealing:
  enabled: false
  # initial_lr: 8.8e-05
load_path: gs://ai2-llm/checkpoints/allysone/anneal-round3-webround2-100B-olmo3_7b_no-reasoning-no-instruct-anneal-12T-6b44f488/step47684
load_state: false
dataset:
  sources:
  - name: web 
    target_ratio: 0.5
    paths:
    - s3://ai2-llm/preprocessed/cc_all_dressed/all_dressed_v3_subsamples/midtrain_pools/6B/allenai/dolma2-tokenizer/*.npy
  
  
  - name: r1_reasoning
    target_ratio: 0.14423
    paths:
    # 2,483,453,165
    - s3://ai2-llm/preprocessed/thinking-data/big-reasoning-traces-reformatted-keyword-filter-datecutoff-chinese-ngram-no-special-tokens-decon-2/allenai/dolma2-tokenizer/*.npy
  
  - name: qwq_reasoning
    target_ratio: 0.14423
    paths:
    # 4,774,150,082
    - s3://ai2-llm/preprocessed/thinking-data/qwq-redo-reformatted-ngram-no-special-tokens-decon-2/allenai/dolma2-tokenizer/*.npy
  
  - name: gemini_reasoning
    target_ratio: 0.01923
    paths:
    # 254,415,258
    - s3://ai2-llm/preprocessed/thinking-data/gemini-redo-reformatted-ngram-no-special-tokens-decon-2/allenai/dolma2-tokenizer/*.npy
  
  - name: llamanemotron_reasoning
    target_ratio: 0.09615
    paths:
    # 20.9B
    - s3://ai2-llm/preprocessed/thinking-data/llama-nemotron-processed-chinese-filtered-ngram-filtered-with-token-counts-decon-2/allenai/dolma2-tokenizer/*.npy
  
  - name: openthoughts2
    target_ratio: 0.09615
    paths:
    # 5,601,836,260
    - s3://ai2-llm/preprocessed/thinking-data/openthoughts2-filtered-chinese-filtered-ngram-filtered-with-token-counts-stripped-decon-2/allenai/dolma2-tokenizer/*.npy
  
  
  # - name: math-meta-reasoning 
  #   target_ratio: 0.3
  #   repetition_factor: 1.5
  #   paths:
  #   - s3://ai2-llm/pretraining-data/sources/midtraining-reasoning/math-meta-reasoning/allenai/dolma2-tokenizer/*.npy
  # - name: code-meta-reasoning 
  #   target_ratio: 0.3
  #   repetition_factor: 1.3
  #   paths:
  #   - s3://ai2-llm/pretraining-data/sources/midtraining-reasoning/code-meta-reasoning/allenai/dolma2-tokenizer/*.npy


  # /model_and_optim/