name: "olm2-7b_10b-anneal_s2c-plablate_py-rust"
description: "OLMo2 7b anneal to 10B Tokens | python + other PL <--- CHANGE THIS"
budget: "ai2/oe-training"
workspace: "ai2/oe-data"
nodes: 4
gpus: 8
preemptible: true
max_tokens: 10_000_000_000
global_batch_size: 2097152
sequence_length: 4096
seed: 1337
model: "olmo2_7B"
tokenizer: "dolma2"
priority: high
eval_interval: 250
learning_rate: 1.8e-3
cluster: ai2/augusta-google-1
rank_microbatch_size: 32768
scheduler_type: linear
warmup_steps: 0
annealing: true
load_path: gs://ai2-llm/checkpoints/OLMo-medium/peteish7/step928646/
load_state: false
weka: false
dataset:
  sources:
  - name: python
    target_ratio: 0.5
    paths:
    - s3://ai2-llm/preprocessed/the-stack-v2/love2code/v0/heuristic_filtered_minhash_plpartition/python/dolma2-tokenizer/*.npy     
  - name: rust
    target_ratio: 0.5 
    paths:
    - s3://ai2-llm/preprocessed/the-stack-v2/love2code/v0/heuristic_filtered_minhash_plpartition/rust/dolma2-tokenizer/*.npy



