name: "suffix-train-olmo2-5xC-30m-dolma2-full-uncompressed-simulated-overlap"
description: "suffix train baseline 30M @ 5xC scale on dolma2 full dataset uncompressed simulated overlap"
budget: "ai2/oe-base"
workspace: "ai2/dolma2"
nodes: 1
gpus: 1
preemptible: true
max_tokens: 3_304_956_112
sequence_length: 2048
global_batch_size: 131072
seed: 1337
learning_rate: 0.007276622186288963
model: "olmo_30m"
tokenizer: "dolma2"
weka: true
priority: high
cluster: ai2/ceres
dataset:
  sources:
    - name: dolma2-full-uncompressed-simulated-overlap
      target_ratio: 1.0
      paths:
        - weka://oe-training-default/ai2-llm/suffix-arrays/preprocessed/dolma2-0625-v01/uncompressed-simulated-overlap-2048/allenai/dolma2-tokenizer/*.npy