name: "suffix-train-olmo2-5xC-30m-dense-dolma2-100B-icl-overlap-suffix"
description: "suffix train baseline 30M @ 5xC scale on dolma2 100B icl overlap suffix"
budget: "ai2/oe-base"
workspace: "ai2/dolma2"
nodes: 1
gpus: 1
preemptible: true
max_tokens: 2_910_233_600
sequence_length: 2048
global_batch_size: 131072
seed: 1337
learning_rate: 0.007276622186288963
model: "olmo_30m"
tokenizer: "dolma2"
weka: false
priority: normal
cluster: ai2/augusta-google-1
dataset:
  sources:
    - name: dolma2-100b-icl-overlap-suffix
      target_ratio: 1.0
      paths:
        - s3://ai2-llm/suffix-arrays/preprocessed/dolma2-0625-samples/100b-suffix-icl-overlap/allenai/dolma2-tokenizer/*.npy
  