name: "olmo-cookbook-3b-5xC-love2code"
description: "Love2Code model, first stab at a config"
budget: "ai2/oe-data"
workspace: "ai2/dolma2"
nodes: 8
gpus: 8
preemptible: true
max_tokens: 348_143_872_000 # 5xC multiplier
sequence_length: 2048
seed: 1337
model: "love2code_3b"
tokenizer: "dolma2"
priority: high
cluster: ai2/jupiter-cirrascale
weka: true
dataset:
  sources:
  - name: dclm-baseline-ft7pct-fw2
    paths: # TODO: ADD ACTUAL PATHS
    - s3://ai2-llm/preprocessed/dclm/v0_rep32_ft7percentile_fw2/documents/allenai/dolma2-tokenizer/0000/part-17-00000.npy

