name: "olmo-cookbook-1b-1xC-sponge-001"
description: "Sponge data olmo-cookbook recipe"
budget: "ai2/oe-data"
workspace: "ai2/dolma2"
nodes: 1
gpus: 8
preemptible: true
max_tokens: 100_000_000
sequence_length: 2048
seed: 1337
model: "olmo2_1B"
tokenizer: "dolma2"
priority: high
cluster: ai2/saturn-cirrascale
weka: true
dataset:
  sources:
  - name: sponge-63
    target_ratio: 1.0
    paths:
    - s3://ai2-llm/preprocessed/sponge/alldressed_63/allenai/dolma2-tokenizer/*/*.npy
