name: "olmo-cookbook-1b-5xC-love2code"
description: "Love2Code model, first stab at a config"
budget: "ai2/oe-training"
workspace: "ai2/oe-data"
nodes: 1
gpus: 8
preemptible: false
max_tokens: 100_000_000
sequence_length: 2048
seed: 1337
model: "olmo_1b"
tokenizer: "dolma2"
priority: high
cluster: ai2/saturn-cirrascale
weka: true
dataset:
  sources:
  - name: the-stack-v2-ai2v0
    target_ratio: 0.85
    paths:
    - weka://oe-training-default/ai2-llm/preprocessed/love2code/stack2_v0_trunc/part-001-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/love2code/stack2_v0_trunc/part-004-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/love2code/stack2_v0_trunc/part-006-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/love2code/stack2_v0_trunc/part-007-00000.npy
  - name: dclm-codeprose-v0
    target_ratio: 0.15
    paths:
    - weka://oe-training-default/ai2-llm/preprocessed/love2code/dclm_codeprose/dolma2-tokenizer/part-00-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/love2code/dclm_codeprose/dolma2-tokenizer/part-01-00000.npy
