name: &name "olmo25_7b_lc_64k_6T_M100B_r5-midtrain_round5_3367_s2pdf_gzip2080_just-synth-cwe-yake_round3web_yarn-fullonly_10B"
description: *name
budget: ai2/oe-base
workspace: ai2/long-contexts
cluster: ai2/augusta-google-1
preemptible: true
priority: urgent
nodes: 8
gpus: 8

seed: 4123
gc_interval: 200
warmup_steps: 200
learning_rate: 0.00020712352850360292
metrics_config:
  backend: wandb
  project: olmo3-7b-long-context
  entity: ai2-llm
generate_doc_lengths: true
load_path: gs://ai2-llm/checkpoints/allysone/anneal-round5-100B-olmo25_7b-anneal-6T-e2b30a73/step47684
load_state: false
model: olmo25_7b_yarn_fullonly
tokenizer: dolma2
max_tokens: 10000000000
global_batch_size: 4194304
sequence_length: 65536
max_target_sequence_length: 65536
rank_microbatch_size: 65536
scheduler_type: linear
dp_shard_degree: 1
cp_degree: 8
cp_head_stride: 8
float8: true
eval_interval: 500
train_module_overrides:
- scheduler.alpha_f=0.0


dataset:
  sources:
  - name: SC-ROUND5-sponge
    target_ratio: 0.0173736214
    paths:
    - s3://ai2-llm/preprocessed/sponge_63_mixes/eli5_60pct_filter-decon-2/**/allenai/dolma2-tokenizer/*.npy
  - name: SC-ROUND5-code_fim
    target_ratio: 0.0347472428
    paths:
    # 21,390,279,634
    - s3://ai2-llm/preprocessed/stack-edu/sample-fim-weighted-pl-edu-score-decon/**/**/*.npy
  - name: SC-ROUND5-swallowcode
    target_ratio: 0.0347472428
    paths:
    # 18,833,636,683
    - s3://ai2-llm/preprocessed/tokyotech-llm/swallowcode/scor_final_data-decon/allenai/dolma2-tokenizer/*.npy
  - name: SC-ROUND5-megamatt
    # 20% less the ratio for dolminos2math
    target_ratio: 0.005900081827
    paths:
    # 3,883,674,937
    - s3://ai2-llm/preprocessed/megamath_web_pro_max/beaker_rewrites-decon-2/allenai/dolma2-tokenizer/*.npy
  - name: SC-ROUND5-dolminos2math
    target_ratio: 0.06359440377
    paths:
    # 5_624_449_531
    - s3://ai2-llm/preprocessed/tokyotech-llm/swallowmath/beaker_outputs-decon-2/allenai/dolma2-tokenizer/*.npy
    # 10,687,987,907
    - s3://ai2-llm/preprocessed/midtraining-reasoning/flat_dolmino_math-decon-2/allenai/dolma2-tokenizer/*.npy
    # 1.99B
    # 850,848,999
    - s3://ai2-llm/preprocessed/midtraining-reasoning/OpenMathReasoning/OpenMathReasoning-rewrite-full-thoughts/jsonls-decon-2/allenai/dolma2-tokenizer/*.npy
    # 898,733,958
    - s3://ai2-llm/preprocessed/midtraining-reasoning/tinyMATH/MIND/data/processed-decon-2/allenai/dolma2-tokenizer/*.npy
    # 240,590,380
    - s3://ai2-llm/preprocessed/midtraining-reasoning/tinyMATH/PoT/processed_data/processed-decon-2/allenai/dolma2-tokenizer/*.npy
  - name: SC-ROUND5-reddit
    target_ratio: 0.02050087325
    paths:
    # 9,860,465,314
    - s3://ai2-llm/preprocessed/reddit-rewrites/densesub_highthresh_microanneal_4omini_rewrite/documents-decon-2/allenai/dolma2-tokenizer/*.npy
    # 21,390,279,634
    - s3://ai2-llm/preprocessed/reddit-rewrites/densesub_lowthresh_4omini_rewrite/documents-decon-2/allenai/dolma2-tokenizer/*.npy
  - name: SC-ROUND5-rcqa
    target_ratio: 0.01042417284
    paths:
    # 4,215,210,848
    - s3://ai2-llm/preprocessed/wiki_psgqa_rewrites/psgqa_rewrites_v1-decon-2/allenai/dolma2-tokenizer/*.npy
  - name: SC-ROUND5-nemotron-synth-qa
    target_ratio: 0.0173736214
    paths:
    # 486,558,362,887
    - s3://ai2-llm/preprocessed/Nemotron-CC/v0/quality=high/kind=synthetic/kind2=diverse_qa_pairs-decon/allenai/dolma2-tokenizer/*.npy
  # - name: SC-ROUND5-instruction
  #   target_ratio: 0
  #   paths:
  #   # 1,627,593,038
  #   - s3://ai2-llm/preprocessed/tulu-3-sft-for-olmo-3-midtraining/raw-decon-2/tulu-3-midtrain-v0-data-simple-concat-with-new-line-with-generation-prompt/allenai/dolma2-tokenizer/*.npy
  - name: SC-ROUND5-instruction-new-format
    target_ratio: 0.003822196708
    paths:
    # 1,639,399,859
    - s3://ai2-llm/preprocessed/tulu-3-sft-for-olmo-3-midtraining/raw/tulu-3-midtrain-v0-data-simple-concat-with-therefore-template-decon/allenai/dolma2-tokenizer/*.npy
  - name: SC-ROUND5-flan
    target_ratio: 0.0173736214
    paths:
    # 17,055,708,123
    - s3://ai2-llm/preprocessed/tulu_flan/v1-FULLDECON-HARD-TRAIN-60M-shots_all-upweight_1-dialog_false-sep_rulebased-decon/allenai/dolma2-tokenizer/*.npy
  - name: SC-ROUND5-r1_reasoning
    target_ratio: 0.006515108024
    paths:
    # 2,483,453,165
    - s3://ai2-llm/preprocessed/thinking-data/big-reasoning-traces-reformatted-keyword-filter-datecutoff-chinese-ngram-no-special-tokens-decon-2/allenai/dolma2-tokenizer/*.npy
  - name: SC-ROUND5-qwq_reasoning
    target_ratio: 0.006515108024
    paths:
    # 4,774,150,082
    - s3://ai2-llm/preprocessed/thinking-data/qwq-redo-reformatted-ngram-no-special-tokens-decon-2/allenai/dolma2-tokenizer/*.npy
  - name: SC-ROUND5-gemini_reasoning
    target_ratio: 0.0008686810699
    paths:
    # 254,415,258
    - s3://ai2-llm/preprocessed/thinking-data/gemini-redo-reformatted-ngram-no-special-tokens-decon-2/allenai/dolma2-tokenizer/*.npy
  - name: SC-ROUND5-llamanemotron_reasoning
    target_ratio: 0.00434340535
    paths:
    # 20.9B
    - s3://ai2-llm/preprocessed/thinking-data/llama-nemotron-processed-chinese-filtered-ngram-filtered-with-token-counts-decon-2/allenai/dolma2-tokenizer/*.npy
  - name: SC-ROUND5-openthoughts2
    target_ratio: 0.00434340535
    paths:
    # 5,601,836,260
    - s3://ai2-llm/preprocessed/thinking-data/openthoughts2-filtered-chinese-filtered-ngram-filtered-with-token-counts-stripped-decon-2/allenai/dolma2-tokenizer/*.npy
  - name: SC-ROUND5-faeze_reasoning
    target_ratio: 0.00347472428
    paths:
    # ORIGINALS
    # 1,198,073,462 --> actually code meta reasoning
    - s3://ai2-llm/preprocessed/midtraining-reasoning/math-meta-reasoning/documents-decon-2/allenai/dolma2-tokenizer/*.npy
    # 366,757,554 --> has special tokens
    # - s3://ai2-llm/preprocessed/midtraining-reasoning/verifiable/gpt-41/documents-decon-2/allenai/dolma2-tokenizer/*.npy
    # 1,198,074,765 --> different version of code meta reasoning
    # - s3://ai2-llm/preprocessed/midtraining-reasoning/code-meta-reasoning/documents-decon-2/allenai/dolma2-tokenizer/*.npy
    ####
    # FIXES
    # 1,049,524,455 --> actual math meta reasoning
    - s3://ai2-llm/preprocessed/midtraining-reasoning/math-meta-reasoning-fixed-decon/allenai/dolma2-tokenizer/*.npy
    # 364,483,656 --> verifiable/gpt-41 without special tokens
    - s3://ai2-llm/preprocessed/midtraining-reasoning/verifiable/gpt-41/cleaned-documents-decon-2/allenai/dolma2-tokenizer/*.npy
    # 73,752,560 --> verifiable/gpt-o4-mini without special tokens
    - s3://ai2-llm/preprocessed/midtraining-reasoning/verifiable/o4-mini-high-decon/allenai/dolma2-tokenizer/*.npy
    ####
    # NEW FORMAT
    # 1,057,302,754 --> actual math meta-reasoning with latex format
    # - s3://ai2-llm/preprocessed/midtraining-reasoning/math-meta-reasoning-latex-delim-decon/allenai/dolma2-tokenizer/*.npy
    # 1,199,242,351 --> actual code meta-reasoning with latex format
    # - s3://ai2-llm/preprocessed/midtraining-reasoning/code-meta-reasoning-latex-delim-decon/allenai/dolma2-tokenizer/*.npy

  - name: SC-ROUND3-web-all_dressed-snazzy2-v20
    target_ratio: 0.0780824897
    paths:
    - s3://ai2-llm/preprocessed/all_dressed_v3_weborganizer_ft_dclm_plus2_vigintiles/vigintile_0020_subset-decon-2/**/allenai/dolma2-tokenizer/*.npy

  # Qwen-3 like setup. From their tech report:
  #
  # > All models are pre-trained on hundreds of billions of tokens with a sequence length of 32,768
  # > tokens. The long context corpus includes 75% of text between 16,384 to 32,768 tokens in length,
  # > and 25% of text between 4,096 to 16,384 in length.
  #
  # Our model was pretrained with 8k length and we want to extend to 64k, so we tweak the recipe to:
  #
  # - 75% of tokens are between 32,768 and 65,536 tokens in length
  # - 25% of tokens are between 8,192 and 32,768 tokens in length


  - name: LC-s2pdf-YAKE_32k-64k
    target_ratio: 0.323
    paths:
      - s3://ai2-llm/preprocessed/LC_synth/yake_s2pdf/olmo32b_s18/length_2e15/allenai/dolma2-tokenizer/*.npy
      - s3://ai2-llm/preprocessed/LC_synth/yake_s2pdf/qwen25-32b_s71/length_2e15/allenai/dolma2-tokenizer/*.npy
      - s3://ai2-llm/preprocessed/LC_synth/yake_s2pdf/gpt5nano_s514/length_2e15/allenai/dolma2-tokenizer/*.npy

  - name: LC-s2pdf-CWE_32k-64k
    target_ratio: 0.18
    paths:
      # total size: 1,491,802,795
      - s3://ai2-llm/preprocessed/LC_synth/cwe_s2pdf/length_2e15/allenai/dolma2-tokenizer/*.npy
      # total size: 467,035,267
      - s3://ai2-llm/preprocessed/LC_synth/cwe_s2pdf/length_2e15_gpt-5-mini-4321/allenai/dolma2-tokenizer/*.npy

  - name: LC-s2pdf_8k-32k
    target_ratio: 0.167
    paths:
      - gs://ai2-llm/preprocessed/s2pdf_dedupe_minhash_v1_with_no_pii_basic_quality_datadelve_norefs_mdtables_v2_denylisted_reshard_length-buckets_compression-decon-2/length_2e13/**/allenai/dolma2-tokenizer/*.npy
      - gs://ai2-llm/preprocessed/s2pdf_dedupe_minhash_v1_with_no_pii_basic_quality_datadelve_norefs_mdtables_v2_denylisted_reshard_length-buckets_compression-decon-2/length_2e14/**/allenai/dolma2-tokenizer/*.npy
