name: "olmo-cookbook-1b-5xC-5shards-dclm_baseline"
description: "5shards-dclm_baseline"
budget: "ai2/oe-data"
workspace: "ai2/olmo3-data-quality"
nodes: 4
gpus: 8
preemptible: true
max_tokens: 140_000_000_000
sequence_length: 2048
global_batch_size: 2097152
lr: 1.8e-3
seed: 1337
model: "olmo2_1B"
tokenizer: "dolma2"
priority: high
cluster: ai2/jupiter-cirrascale-2
wandb:
  project: "olmo3-data-quality"
dataset:
  sources:
  - name: "5shards-dclm_baseline"
    target_ratio: 1.0
    repetition_factor: 1.0
    paths:
    - "s3://ai2-llm/preprocessed/dclm/ablations/5shards-dclm_baseline/*.npy"
downstream_evaluators:
- arc_challenge_test_rc_5shot
- arc_easy_test_rc_5shot
- hellaswag_rc_5shot
- winogrande_val_rc_5shot
- csqa_val_rc_5shot
- piqa_val_rc_5shot
- socialiqa_val_rc_5shot
- mmlu_stem_val_rc_5shot
- mmlu_humanities_val_rc_5shot
- mmlu_social_sciences_val_rc_5shot
- mmlu_other_val_rc_5shot
- mmlu_stem_test_rc_5shot
- mmlu_humanities_test_rc_5shot
- mmlu_social_sciences_test_rc_5shot
- mmlu_other_test_rc_5shot
- gsm8k_gold_bpb_5shot
- minerva_math_algebra_gold_bpb_0shot
- minerva_math_counting_and_probability_gold_bpb_0shot
- minerva_math_geometry_gold_bpb_0shot
- minerva_math_intermediate_algebra_gold_bpb_0shot
- minerva_math_number_theory_gold_bpb_0shot
- minerva_math_prealgebra_gold_bpb_0shot
- minerva_math_precalculus_gold_bpb_0shot
- codex_humaneval_gold_bpb_0shot
- codex_mbpp_gold_bpb_0shot
- copycolors_10way
lm_evaluator: true