name: "olmo-cookbook-core-v2-1bv2-5xC-dclm-baseline-topic-classified-sample-repeats-1-4e-4"
description: "Olmo-cookbook 1Bv2-5xC on dclm baseline, swarm 62e7dc06 run 117 (requires repetition), 4e-4"
budget: "ai2/oe-data"
workspace: "ai2/oe-data" #"ai2/dolma2"
nodes: 4
gpus: 8
preemptible: true
max_tokens: 127_939_584_000 # for olmo2_1B_v2, we have  1_279_395_840 non-embedding params
sequence_length: 4096 #4096, 2048
seed: 1337
model: "olmo2_1B_v2"
tokenizer: "dolma2"
priority: high
cluster: ai2/jupiter-cirrascale-2
weka: true
rank_microbatch_size: 32_768
global_batch_size: 2_097_152 # 4_194_304, 2_097_152
learning_rate: 4e-4
dataset:
  sources:
  - name: electronics_and_hardware
    paths:
      - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/electronics_and_hardware/dolma2-tokenizer/*.npy
    target_ratio: 0.09523809523809525
    repetition_factor: 1.05
  - name: health
    paths:
      - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/health/dolma2-tokenizer/*.npy
    target_ratio: 0.09523809523809525
  - name: politics
    paths:
      - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/politics/dolma2-tokenizer/*.npy
    target_ratio: 0.047619047619047616
  - name: science_math_and_technology
    paths:
      - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/science_math_and_technology/dolma2-tokenizer/*.npy
    target_ratio: 0.6190476190476191
    repetition_factor: 1.3
  - name: software_development
    paths:
      - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/software_development/dolma2-tokenizer/*.npy
    target_ratio: 0.14285714285714288
downstream_evaluators:
- arc_challenge_test_rc_5shot
- arc_easy_test_rc_5shot
- hellaswag_rc_5shot
- winogrande_val_rc_5shot
- csqa_val_rc_5shot
- piqa_val_rc_5shot
- socialiqa_val_rc_5shot
- mmlu_stem_val_rc_5shot
- mmlu_humanities_val_rc_5shot
- mmlu_social_sciences_val_rc_5shot
- mmlu_other_val_rc_5shot
- mmlu_stem_test_rc_5shot
- mmlu_humanities_test_rc_5shot
- mmlu_social_sciences_test_rc_5shot
- mmlu_other_test_rc_5shot
- gsm8k_gold_bpb_5shot
- minerva_math_algebra_gold_bpb_0shot
- minerva_math_counting_and_probability_gold_bpb_0shot
- minerva_math_geometry_gold_bpb_0shot
- minerva_math_intermediate_algebra_gold_bpb_0shot
- minerva_math_number_theory_gold_bpb_0shot
- minerva_math_prealgebra_gold_bpb_0shot
- minerva_math_precalculus_gold_bpb_0shot
- codex_humaneval_gold_bpb_0shot
- codex_mbpp_gold_bpb_0shot
- copycolors_10way
lm_evaluator: true