name: "olmo3_7b_web-only-anneal-round2mix-12T-10B-pstar-v20-1337"
description: "OLMo3 7b microanneal to 10B Tokens on pstar (web only)"
budget: "ai2/oe-base"
workspace: "ai2/oe-data"
nodes: 2
gpus: 8
preemptible: true
max_tokens: 10_000_000_000
global_batch_size: 2097152
sequence_length: 8192
seed: 1337
model: "olmo2_7B_swafix"
tokenizer: "dolma2"
priority: high
cluster: ai2/augusta-google-1
rank_microbatch_size: 16384
scheduler_type: linear
warmup_steps: 0
activation_checkpointing: true
annealing:
  enabled: true
load_path: gs://ai2-llm/checkpoints/OLMo3-7B-swafix/step756906 # 12T tokens
load_state: false
dataset:
  sources:
  - name: web-all_dressed-snazzy2-v18-v20-adult_content
    target_ratio: 0.001136416
    paths:
    - s3://ai2-llm/preprocessed/cc_all_dressed/all_dressed_v3/dclm_plus2_vigilantes/allenai/dolma2-tokenizer/adult_content/vigintile_0020/*.npy
  - name: web-all_dressed-snazzy2-v18-v20-art_and_design
    target_ratio: 0.012551282
    paths:
    - s3://ai2-llm/preprocessed/cc_all_dressed/all_dressed_v3/dclm_plus2_vigilantes/allenai/dolma2-tokenizer/art_and_design/vigintile_0020/*.npy
  - name: web-all_dressed-snazzy2-v18-v20-crime_and_law
    target_ratio: 0.029282202
    paths:
    - s3://ai2-llm/preprocessed/cc_all_dressed/all_dressed_v3/dclm_plus2_vigilantes/allenai/dolma2-tokenizer/crime_and_law/vigintile_0020/*.npy
  - name: web-all_dressed-snazzy2-v18-v20-education_and_jobs
    target_ratio: 0.04290644
    paths:
    - s3://ai2-llm/preprocessed/cc_all_dressed/all_dressed_v3/dclm_plus2_vigilantes/allenai/dolma2-tokenizer/education_and_jobs/vigintile_0020/*.npy
  - name: web-all_dressed-snazzy2-v18-v20-electronics_and_hardware
    target_ratio: 0.034638173
    paths:
    - s3://ai2-llm/preprocessed/cc_all_dressed/all_dressed_v3/dclm_plus2_vigilantes/allenai/dolma2-tokenizer/electronics_and_hardware/vigintile_0020/*.npy
  - name: web-all_dressed-snazzy2-v18-v20-entertainment
    target_ratio: 0.09603404
    paths:
    - s3://ai2-llm/preprocessed/cc_all_dressed/all_dressed_v3/dclm_plus2_vigilantes/allenai/dolma2-tokenizer/entertainment/vigintile_0020/*.npy
  - name: web-all_dressed-snazzy2-v18-v20-fashion_and_beauty
    target_ratio: 0.000127422
    paths:
    - s3://ai2-llm/preprocessed/cc_all_dressed/all_dressed_v3/dclm_plus2_vigilantes/allenai/dolma2-tokenizer/fashion_and_beauty/vigintile_0020/*.npy
  - name: web-all_dressed-snazzy2-v18-v20-finance_and_business
    target_ratio: 0.040632245
    paths:
    - s3://ai2-llm/preprocessed/cc_all_dressed/all_dressed_v3/dclm_plus2_vigilantes/allenai/dolma2-tokenizer/finance_and_business/vigintile_0020/*.npy
  - name: web-all_dressed-snazzy2-v18-v20-food_and_dining
    target_ratio: 0.014058818
    paths:
    - s3://ai2-llm/preprocessed/cc_all_dressed/all_dressed_v3/dclm_plus2_vigilantes/allenai/dolma2-tokenizer/food_and_dining/vigintile_0020/*.npy
  - name: web-all_dressed-snazzy2-v18-v20-games
    target_ratio: 0.068861807
    paths:
    - s3://ai2-llm/preprocessed/cc_all_dressed/all_dressed_v3/dclm_plus2_vigilantes/allenai/dolma2-tokenizer/games/vigintile_0020/*.npy
  - name: web-all_dressed-snazzy2-v18-v20-health
    target_ratio: 0.099577625
    paths:
    - s3://ai2-llm/preprocessed/cc_all_dressed/all_dressed_v3/dclm_plus2_vigilantes/allenai/dolma2-tokenizer/health/vigintile_0020/*.npy
  - name: web-all_dressed-snazzy2-v18-v20-history_and_geography
    target_ratio: 0.027193618
    paths:
    - s3://ai2-llm/preprocessed/cc_all_dressed/all_dressed_v3/dclm_plus2_vigilantes/allenai/dolma2-tokenizer/history_and_geography/vigintile_0020/*.npy
  - name: web-all_dressed-snazzy2-v18-v20-home_and_hobbies
    target_ratio: 0.00914884
    paths:
    - s3://ai2-llm/preprocessed/cc_all_dressed/all_dressed_v3/dclm_plus2_vigilantes/allenai/dolma2-tokenizer/home_and_hobbies/vigintile_0020/*.npy
  - name: web-all_dressed-snazzy2-v18-v20-industrial
    target_ratio: 0.015704927
    paths:
    - s3://ai2-llm/preprocessed/cc_all_dressed/all_dressed_v3/dclm_plus2_vigilantes/allenai/dolma2-tokenizer/industrial/vigintile_0020/*.npy
  - name: web-all_dressed-snazzy2-v18-v20-literature
    target_ratio: 0.068181396
    paths:
    - s3://ai2-llm/preprocessed/cc_all_dressed/all_dressed_v3/dclm_plus2_vigilantes/allenai/dolma2-tokenizer/literature/vigintile_0020/*.npy
  - name: web-all_dressed-snazzy2-v18-v20-politics
    target_ratio: 0.021624593
    paths:
    - s3://ai2-llm/preprocessed/cc_all_dressed/all_dressed_v3/dclm_plus2_vigilantes/allenai/dolma2-tokenizer/politics/vigintile_0020/*.npy
  - name: web-all_dressed-snazzy2-v18-v20-religion
    target_ratio: 0.019762269
    paths:
    - s3://ai2-llm/preprocessed/cc_all_dressed/all_dressed_v3/dclm_plus2_vigilantes/allenai/dolma2-tokenizer/religion/vigintile_0020/*.npy
  - name: web-all_dressed-snazzy2-v18-v20-science_math_and_technology
    target_ratio: 0.210248843
    paths:
    - s3://ai2-llm/preprocessed/cc_all_dressed/all_dressed_v3/dclm_plus2_vigilantes/allenai/dolma2-tokenizer/science_math_and_technology/vigintile_0020/*.npy
  - name: web-all_dressed-snazzy2-v18-v20-social_life
    target_ratio: 0.004601218
    paths:
    - s3://ai2-llm/preprocessed/cc_all_dressed/all_dressed_v3/dclm_plus2_vigilantes/allenai/dolma2-tokenizer/social_life/vigintile_0020/*.npy
  - name: web-all_dressed-snazzy2-v18-v20-software_development
    target_ratio: 0.047331427
    paths:
    - s3://ai2-llm/preprocessed/cc_all_dressed/all_dressed_v3/dclm_plus2_vigilantes/allenai/dolma2-tokenizer/software_development/vigintile_0020/*.npy
  - name: web-all_dressed-snazzy2-v18-v20-software
    target_ratio: 0.111466505
    paths:
    - s3://ai2-llm/preprocessed/cc_all_dressed/all_dressed_v3/dclm_plus2_vigilantes/allenai/dolma2-tokenizer/software/vigintile_0020/*.npy
  - name: web-all_dressed-snazzy2-v18-v20-sports_and_fitness
    target_ratio: 0.012994744
    paths:
    - s3://ai2-llm/preprocessed/cc_all_dressed/all_dressed_v3/dclm_plus2_vigilantes/allenai/dolma2-tokenizer/sports_and_fitness/vigintile_0020/*.npy
  - name: web-all_dressed-snazzy2-v18-v20-transportation
    target_ratio: 0.009746536
    paths:
    - s3://ai2-llm/preprocessed/cc_all_dressed/all_dressed_v3/dclm_plus2_vigilantes/allenai/dolma2-tokenizer/transportation/vigintile_0020/*.npy
  - name: web-all_dressed-snazzy2-v18-v20-travel_and_tourism
    target_ratio: 0.002188616
    paths:
    - s3://ai2-llm/preprocessed/cc_all_dressed/all_dressed_v3/dclm_plus2_vigilantes/allenai/dolma2-tokenizer/travel_and_tourism/vigintile_0020/*.npy
