name: "spring2code-190m-5xC-python-fim-hlr"
description: "learn2code 190M@5xC python-only with fim transformation + dclm prose v2"
budget: "ai2/oe-training"
workspace: "ai2/oe-data"
nodes: 2
gpus: 8
preemptible: true
max_tokens: 19_000_000_000
sequence_length: 2048
seed: 1337
model: "olmo2_190M"
tokenizer: "dolma2" # how to set?
priority: high
eval_interval: 100
global_batch_size: 1_048_576 # Half of the 1B
learning_rate: 1.8e-3
cluster: ai2/jupiter-cirrascale-2
weka: true
downstream_evaluators:
  - codex_humaneval_gold_bpb_0shot
  - codex_mbpp_gold_bpb_0shot
dataset:
  sources:
  - name: the-stack-v2-fimv0
    target_ratio: 0.85
    paths:
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/spring2code-fim-test/allenai/dolma2-tokenizer/0000/part-00-00000.npy

  - name: dclm-codeprose-v2
    target_ratio: 0.15
    paths:
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-000-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-001-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-002-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-003-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-004-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-005-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-006-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-007-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-008-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-009-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-010-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-011-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-012-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-013-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-014-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-015-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-016-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-017-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-018-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-019-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-020-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-021-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-022-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-023-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-024-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-025-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-026-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-027-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-028-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-029-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-030-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-031-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-032-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-033-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-034-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-035-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-036-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-037-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-038-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-039-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-040-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-041-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-042-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-043-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-044-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-045-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-046-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-047-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-048-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-049-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-050-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-051-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-052-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-053-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-054-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-055-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-056-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-057-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-058-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-059-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-060-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-061-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-062-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-063-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-064-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-065-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-066-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-067-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-068-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-069-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-070-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-071-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-072-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-073-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-074-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-075-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-076-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-077-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-078-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-079-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-080-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-081-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-082-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-083-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-084-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-085-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-086-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-087-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-088-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-089-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-090-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-091-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-092-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-093-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-094-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-095-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-096-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-097-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-098-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-099-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-100-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-101-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-102-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-103-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-104-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-105-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-106-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-107-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-108-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-109-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-110-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-111-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-112-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-113-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-114-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-115-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-116-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-117-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-118-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-119-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-120-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-121-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-122-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-123-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-124-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-125-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-126-00000.npy
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/20b-sample/allenai/dolma2-tokenizer/part-127-00000.npy
