name: "spring2code-1b-5xC-top15-hlr-superbpe"
description: "learn2code 1b@5xC top15 langauges from the-stack-v2 + dclm prose v2"
budget: "ai2/oe-training"
workspace: "ai2/oe-data"
nodes: 4
gpus: 8
preemptible: true
max_tokens: 113_184_153_600
sequence_length: 2048
seed: 1337
model: "olmo2_1B"
tokenizer: "dolma2"
priority: high
eval_interval: 250
learning_rate: 1.8e-3
cluster: ai2/jupiter-cirrascale-2
weka: true
downstream_evaluators:
  - codex_humaneval_gold_bpb_0shot
  - codex_mbpp_gold_bpb_0shot
dataset:
  sources:
  - name: the-stack-v2-top15-ai2v0-minhash-10pct-superbpe
    target_ratio: 0.85
    paths:
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/love2code-top15-minhash-plpartition-10pct/allenai/superbpe-olmo3-experimental/**/*.npy
  - name: dclm-codeprose-v2-superbpe
    target_ratio: 0.15
    paths:
    - weka://oe-training-default/ai2-llm/preprocessed/learn2code/dclm-prose-v2/all/allenai/superbpe-olmo3-experimental/**/*.npy
