name: "olmo3-microanneal-olmo3-mix"
description: "OLMo3 7B microanneal to 10B Tokens from OLMo 3 mix "
budget: "ai2/oe-training"
workspace: "ai2/oe-data"
nodes: 2
gpus: 8
preemptible: true
max_tokens: 10_000_000_000
global_batch_size: 2097152
sequence_length: 8192
seed: 1337
model: "olmo2_7B_swafix"
tokenizer: "dolma2"
priority: urgent
cluster: ai2/augusta-google-1
rank_microbatch_size: 16384
scheduler_type: linear
warmup_steps: 0
activation_checkpointing: true
annealing:
  enabled: true
load_path: gs://ai2-llm/checkpoints/OLMo3-7B-swafix/step289000
load_state: false
downstream_evaluators:
  - olmo2_dev_1b
dataset:
  sources:
  - name: all_dressed-snazzy2
    target_ratio: 1.0
    paths:
    - gs://ai2-llm/preprocessed/dolma2-0625/v0.1/allenai/dolma2-tokenizer/all-dressed-snazzy2/**/*.npy
